name: build
on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]
jobs:
	build:
		runs-on: windows-latest
		steps:
		- name: checkout source
		- uses: actions/checkout@v2
		
		
		- name: Setup .NET Core SDK
		  uses: actions/setup-dotnet@v1.7.2
		  with:
		    # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
		    dotnet-version: # optional
		    # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
		    source-url: # optional
		    # Optional OWNER for using packages from GitHub Package Registry organizations/users other than the current repository's owner. Only used if a GPR URL is also provided in source-url
		    owner: # optional
		    # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.
		    config-file: # optional
		
		- name: Setup .Net Core
		  uses: actions/setup-dotnet@v1
		  with:
			dotnet-version: 5.0.x
		- name: Install dependencies
		  run: dotnet restore
		  working-directory: Phase05/app

		- name: Build
		  run: dotnet build --configuration Release --no-restore
		  working-directory: Phase05/app

		- name: Test
		  run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
		  working-directory: Phase05/app     
	
